#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# claude-agent-teams.sh
#   Claude Agent Team tmux 레이아웃 자동 구성기
#   - -agent N: 총 N명 (Team Leader 1 + Agent N-1)
#   - 모든 pane에 'claude' 자동 실행 + 팀 오케스트레이션 헬퍼 생성
#   - 임의 디렉토리 / 임의 세션 이름 지원
#   - 자체 완결형 스타일링 (~/.tmux.conf 불필요)
# ============================================================

TEAM_SIZE=1
SESSION=""          # 비우면 아래에서 디렉토리 기반으로 자동 생성
DIR="$PWD"
NO_ATTACH=0

usage() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Options:
  -agent N          총 팀 인원 (Team Leader 1 + Agent N-1), N: 1..11 (기본: 1, 리더만)
  -dir PATH         모든 pane의 작업 디렉토리 (기본: 현재 디렉토리)
  -session NAME     tmux 세션 이름 (기본: claude-team-<디렉토리명>)
  -no-attach        세션 생성 후 attach/switch-client 생략 (수동 attach용)
  -h, --help        이 도움말

Examples:
  $(basename "$0")                          # 기본: Team Leader 혼자 (총 1)
  $(basename "$0") -agent 4                 # Team Leader + Agent 3
  $(basename "$0") -agent 6 -dir ~/work/app # Team Leader + Agent 5
  $(basename "$0") -agent 4 -session dev    # 세션 이름 지정

레이아웃:
  ┌──────────────┬──────────────┐
  │              │  Agent-1     │
  │  Team Leader ├──────────────┤
  │              │  Agent-2     │
  │              ├──────────────┤
  │              │  Agent-3     │
  └──────────────┴──────────────┘

동작:
  - 작업 디렉토리에 .claude-team/ 폴더 생성 (Leader 헬퍼)
  - .claude-team/team 으로 Team Leader가 Agent에게 명령 전달
  - 같은 이름 세션이 있으면 kill 후 재생성
  - tmux 안: switch-client / 밖: attach / 비-TTY: 안내만 출력
EOF
}

# ── 인자 파싱 ────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    -agent)     TEAM_SIZE="${2:-}"; shift 2 ;;
    -dir)       DIR="${2:-}"; shift 2 ;;
    -session)   SESSION="${2:-}"; shift 2 ;;
    -no-attach) NO_ATTACH=1; shift ;;
    -h|--help)  usage; exit 0 ;;
    *)          echo "알 수 없는 옵션: $1" >&2; usage; exit 1 ;;
  esac
done

# ── 유효성 검사 ──────────────────────────────────────────────
if ! [[ "$TEAM_SIZE" =~ ^[0-9]+$ ]]; then
  echo "Error: -agent은 숫자여야 함 (1-11)" >&2; exit 1
fi
if (( TEAM_SIZE < 1 )); then
  echo "Error: -agent 최소값은 1 (Team Leader만)" >&2; exit 1
fi
if (( TEAM_SIZE > 11 )); then
  echo "Error: 최대 11명 (Team Leader + Agent 10)" >&2; exit 1
fi

AGENT_COUNT=$((TEAM_SIZE - 1))   # Leader 제외 작업 에이전트 수

DIR="${DIR/#\~/$HOME}"
if [[ ! -d "$DIR" ]]; then
  echo "Error: 디렉토리 없음: $DIR" >&2; exit 1
fi
DIR=$(cd "$DIR" && pwd)

# 세션 이름 미지정 시 디렉토리 기반 자동 생성 (여러 디렉토리 동시 실행 가능)
if [[ -z "$SESSION" ]]; then
  SLUG=$(basename "$DIR" | tr -c '[:alnum:]_-' '-' | sed 's/-\+/-/g; s/^-//; s/-$//')
  [[ -z "$SLUG" ]] && SLUG="root"
  SESSION="claude-team-$SLUG"
fi

if ! command -v claude >/dev/null 2>&1; then
  echo "Warning: 'claude' 명령을 PATH에서 찾을 수 없음 — pane이 즉시 종료될 수 있음" >&2
fi

CLAUDE_CMD="claude"

# ── 팀 헬퍼 생성 ─────────────────────────────────────────────
write_team_helper() {
  local team_dir="$DIR/.claude-team"
  mkdir -p "$team_dir"

  cat > "$team_dir/team" <<TEAMEOF
#!/usr/bin/env bash
# Auto-generated by claude-agent-teams.sh
# Session: $SESSION  Agents: $AGENT_COUNT
set -euo pipefail

SESSION="$SESSION"
AGENT_COUNT=$AGENT_COUNT

usage() {
  cat <<EOF
Usage: \$(basename "\$0") <command> [args]

Commands:
  list                         팀원 목록
  send <N> <message...>        Agent-N에게 메시지 전송 (Enter 포함)
  broadcast <message...>       모든 Agent에게 메시지
  view <N> [lines]             Agent-N pane 최근 내용 (기본 30줄)
  leader <message...>          Team Leader pane에 메시지 (테스트용)
  status                       각 pane 상태 요약

Examples:
  ./.claude-team/team list
  ./.claude-team/team send 1 "src/foo.ts 리뷰해줘"
  ./.claude-team/team broadcast "현재 상태 보고"
  ./.claude-team/team view 2 50
EOF
}

check_session() {
  if ! tmux has-session -t "\$SESSION" 2>/dev/null; then
    echo "Error: 세션 '\$SESSION' 없음 (이미 종료됨)" >&2
    exit 1
  fi
}

check_agent_num() {
  local n="\$1"
  if ! [[ "\$n" =~ ^[0-9]+\$ ]]; then
    echo "Error: agent 번호는 숫자여야 함" >&2; exit 1
  fi
  if (( n < 1 || n > AGENT_COUNT )); then
    echo "Error: agent 번호 범위: 1..\$AGENT_COUNT" >&2; exit 1
  fi
}

send_to_pane() {
  local pane="\$1" msg="\$2"
  tmux send-keys -t "\$pane" -l "\$msg"
  tmux send-keys -t "\$pane" Enter
}

SUBCMD="\${1:-}"
shift || true

case "\$SUBCMD" in
  list)
    check_session
    echo "Session: \$SESSION"
    echo "  0 → Team Leader (\$SESSION:0.0)"
    for ((i=1; i<=AGENT_COUNT; i++)); do
      echo "  \$i → Agent-\$i     (\$SESSION:0.\$i)"
    done
    ;;
  send)
    check_session
    N="\${1:?agent number required}"
    shift
    check_agent_num "\$N"
    MSG="\$*"
    [[ -z "\$MSG" ]] && { echo "message required" >&2; exit 1; }
    send_to_pane "\$SESSION:0.\$N" "\$MSG"
    echo "→ Agent-\$N: \$MSG"
    ;;
  broadcast)
    check_session
    MSG="\$*"
    [[ -z "\$MSG" ]] && { echo "message required" >&2; exit 1; }
    for ((i=1; i<=AGENT_COUNT; i++)); do
      send_to_pane "\$SESSION:0.\$i" "\$MSG"
    done
    echo "→ All agents (\$AGENT_COUNT): \$MSG"
    ;;
  view)
    check_session
    N="\${1:?agent number required}"
    check_agent_num "\$N"
    LINES="\${2:-30}"
    tmux capture-pane -pt "\$SESSION:0.\$N" -S "-\$LINES"
    ;;
  leader)
    check_session
    MSG="\$*"
    [[ -z "\$MSG" ]] && { echo "message required" >&2; exit 1; }
    send_to_pane "\$SESSION:0.0" "\$MSG"
    echo "→ Team Leader: \$MSG"
    ;;
  status)
    check_session
    printf "%-14s %-22s %s\n" "Role" "Pane" "Running"
    printf "%-14s %-22s %s\n" "----" "----" "-------"
    for ((i=0; i<=AGENT_COUNT; i++)); do
      role=\$([[ \$i -eq 0 ]] && echo "Team Leader" || echo "Agent-\$i")
      cmd=\$(tmux display-message -pt "\$SESSION:0.\$i" '#{pane_current_command}' 2>/dev/null || echo "?")
      printf "%-14s %-22s %s\n" "\$role" "\$SESSION:0.\$i" "\$cmd"
    done
    ;;
  ""|-h|--help)
    usage
    ;;
  *)
    echo "Unknown command: \$SUBCMD" >&2
    usage
    exit 1
    ;;
esac
TEAMEOF
  chmod +x "$team_dir/team"

  cat > "$team_dir/README.md" <<READMEEOF
# Claude Agent Team

자동 생성됨. \`claude-agent-teams.sh -agent $TEAM_SIZE\` 으로 만든 팀 세션용 헬퍼.

- **세션**: \`$SESSION\`
- **총 인원**: $TEAM_SIZE (Team Leader 1 + Agent $AGENT_COUNT)
- **작업 디렉토리**: \`$DIR\`

## 구조

- **Team Leader** (pane 0, 왼쪽) — 조율 담당
- **Agent-1..$AGENT_COUNT** (pane 1..$AGENT_COUNT, 오른쪽 세로 스택) — 작업 수행

## Team Leader에서 사용법

Team Leader pane의 Claude는 Bash 툴로 아래 명령을 호출하여 팀원을 조종할 수 있다:

\`\`\`bash
./.claude-team/team list                            # 팀원 목록
./.claude-team/team send 1 "src/foo.ts 리뷰해줘"     # Agent-1에 작업 지시
./.claude-team/team send 2 "테스트 작성해줘: bar.ts" # Agent-2에 작업 지시
./.claude-team/team broadcast "현재 상태 보고"       # 모두에게
./.claude-team/team view 1                          # Agent-1 pane 보기
./.claude-team/team view 1 100                      # 최근 100줄
./.claude-team/team status                          # 각 pane 실행 상태
\`\`\`

## 동작 원리

- 각 pane은 **독립적인 Claude Code 인스턴스**
- \`team send N "..."\` 는 \`tmux send-keys\` 로 Agent-N pane에 메시지를 타이핑하고 Enter → Agent의 claude가 그걸 사용자 입력으로 처리
- 응답은 Agent pane에서 직접 보거나 \`team view N\` 으로 캡처

## 정리

세션 종료 후 이 폴더는 안전하게 삭제 가능:

\`\`\`bash
rm -rf ./.claude-team
\`\`\`
READMEEOF
}

# ── 세션 재생성 ──────────────────────────────────────────────
# 현재 attach된 세션과 동명이면 kill 금지 (본인 터미널/클로드 세션 보호)
if [[ -n "${TMUX:-}" ]]; then
  CURRENT_SESSION=$(tmux display-message -p '#{session_name}' 2>/dev/null || echo "")
  if [[ "$CURRENT_SESSION" == "$SESSION" ]]; then
    echo "Error: 현재 attach 중인 세션 '$SESSION' 은 재생성 불가. -session 으로 다른 이름 지정." >&2
    exit 1
  fi
fi
tmux kill-session -t "$SESSION" 2>/dev/null || true

# history-limit은 pane 생성 시점에 고정됨 → new-session 전에 설정
tmux set-option -g history-limit 50000 >/dev/null

tmux new-session -d -s "$SESSION" -n main -c "$DIR" "$CLAUDE_CMD"

# ── 스타일링 (세션 스코프, 자체 완결) ───────────────────────
tmux set-option -t "$SESSION" mouse on
tmux set-option -t "$SESSION" pane-border-status top
tmux set-option -t "$SESSION" pane-border-lines heavy
tmux set-option -t "$SESSION" pane-border-style "fg=colour39"
tmux set-option -t "$SESSION" pane-active-border-style "fg=colour39,bold"
tmux set-option -t "$SESSION" pane-border-format \
  '#{?pane_active,#[fg=colour15#,bg=colour27#,bold] ━━ #{@role} ━━ ,#[fg=colour39#,bg=default] #{@role} }'

# 마우스 휠 → 스크롤백 (copy-mode 자동 진입 + 즉시 위로 스크롤)
tmux bind-key -T root WheelUpPane \
  if-shell -F -t = "#{pane_in_mode}" "send-keys -M" "copy-mode -eu"
tmux bind-key -T copy-mode    WheelUpPane   send-keys -X -N 5 scroll-up
tmux bind-key -T copy-mode    WheelDownPane send-keys -X -N 5 scroll-down
tmux bind-key -T copy-mode-vi WheelUpPane   send-keys -X -N 5 scroll-up
tmux bind-key -T copy-mode-vi WheelDownPane send-keys -X -N 5 scroll-down

# ── pane 구성 ────────────────────────────────────────────────
LEADER=$(tmux display-message -t "$SESSION:main" -p '#{pane_id}')
tmux set-option -pt "$LEADER" @role "Team Leader"

if (( AGENT_COUNT >= 1 )); then
  AGENT1=$(tmux split-window -h -t "$LEADER" -c "$DIR" -P -F '#{pane_id}' "$CLAUDE_CMD")
  tmux set-option -pt "$AGENT1" @role "Agent-1"
  AGENT_IDS=("$AGENT1")

  PREV="$AGENT1"
  for ((i=2; i<=AGENT_COUNT; i++)); do
    NEW=$(tmux split-window -v -t "$PREV" -c "$DIR" -P -F '#{pane_id}' "$CLAUDE_CMD")
    tmux set-option -pt "$NEW" @role "Agent-$i"
    AGENT_IDS+=("$NEW")
    PREV="$NEW"
  done

  W_WIDTH=$(tmux display-message -t "$LEADER" -p '#{window_width}')
  tmux resize-pane -t "$LEADER" -x $((W_WIDTH / 2))

  if (( AGENT_COUNT > 1 )); then
    W_HEIGHT=$(tmux display-message -t "$LEADER" -p '#{window_height}')
    EACH=$(( (W_HEIGHT - 1) / AGENT_COUNT ))
    (( EACH < 3 )) && EACH=3
    for id in "${AGENT_IDS[@]}"; do
      tmux resize-pane -t "$id" -y "$EACH" 2>/dev/null || true
    done
  fi
fi

tmux select-pane -t "$LEADER"

# ── 팀 헬퍼 생성 + 안내 ──────────────────────────────────────
if (( AGENT_COUNT >= 1 )); then
  write_team_helper
  cat <<BANNER >&2

✓ Claude Agent Team 준비 완료
  팀: Team Leader + Agent $AGENT_COUNT (총 $TEAM_SIZE명)
  작업 디렉토리: $DIR
  헬퍼: ./.claude-team/team (README: ./.claude-team/README.md)

  Team Leader에서 예시:
    ./.claude-team/team list
    ./.claude-team/team send 1 "src/foo.ts 리뷰해줘"
    ./.claude-team/team broadcast "상태 보고"

BANNER
fi

# ── attach / switch ──────────────────────────────────────────
# TTY가 아니면(파이프/Claude Bash 툴 등) attach 생략 → 호출측 세션 보호
if (( NO_ATTACH )) || [[ ! -t 1 ]]; then
  cat <<HINT >&2
✓ 세션 '$SESSION' 생성 완료 (attach 생략됨)
  수동 attach:
    tmux attach -t $SESSION        # tmux 밖에서
    tmux switch-client -t $SESSION # tmux 안에서
HINT
  exit 0
fi

if [[ -n "${TMUX:-}" ]]; then
  tmux switch-client -t "$SESSION"
else
  tmux attach-session -t "$SESSION"
fi
