#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# claude-subagent.sh
#   Claude 서브에이전트 tmux 레이아웃 자동 구성기
#   - -team NAME [PROMPT]: 팀 등록 (최대 10팀)
#   - 모든 pane에 'claude' 자동 실행
#   - PROMPT 지정 시 claude 기동 후 자동 주입
#   - pane 레이블: "Subagent / Team Leader" / "Agent-N"
#   - .claude-subagent/team 헬퍼: 이름 또는 번호로 팀 조종
# ============================================================

SESSION=""
DIR="$PWD"
NO_ATTACH=0
TEAM_NAMES=()
TEAM_PROMPTS=()
AGENT_SIZE=0   # -agent N 으로 지정 시 (N = Team Leader 포함 총 인원)

usage() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Options:
  -agent N              총 팀 인원 (Team Leader 1 + Agent N-1), N: 2..11
  -team NAME [PROMPT]   이름 기반 팀 등록. PROMPT: 파일경로 or "인라인" (선택)
                        (여러 번 사용 가능, 최대 10팀)
  -dir PATH             작업 디렉토리 (기본: 현재)
  -session NAME         tmux 세션 이름 (기본: subagent-<디렉토리명>)
  -no-attach            세션 생성 후 attach 생략
  -h, --help            도움말

Examples:
  # 번호 기반 (agentteams와 동일한 방식)
  $(basename "$0") -agent 3

  # 이름 기반 (프롬프트 없이)
  $(basename "$0") -team interface -team infra -team fe

  # 이름 기반 + 초기 프롬프트 자동 주입
  $(basename "$0") \\
    -team interface prompts/interface.md \\
    -team infra     prompts/infra.md \\
    -team fe        prompts/fe.md

레이아웃:
  ┌──────────────────────┬──────────────┐
  │                      │  Agent-1     │
  │  Subagent /          ├──────────────┤
  │  Team Leader         │  Agent-2     │
  │                      ├──────────────┤
  │                      │  Agent-3     │
  └──────────────────────┴──────────────┘

헬퍼 (Team Leader pane에서):
  ./.claude-subagent/team list
  ./.claude-subagent/team send interface "작업 지시"   # 이름으로 (-team 사용 시)
  ./.claude-subagent/team send 1 "작업 지시"           # 번호로 (항상 가능)
  ./.claude-subagent/team broadcast "전체 공지"
  ./.claude-subagent/team view 2
  ./.claude-subagent/team status
EOF
}

# ── 인자 파싱 ────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    -agent)
      AGENT_SIZE="${2:-}"; shift 2
      ;;
    -team)
      [[ -n "${2:-}" ]] || { echo "Error: -team NAME 필요" >&2; exit 1; }
      TEAM_NAMES+=("$2")
      if [[ -n "${3:-}" ]] && [[ "$3" != -* ]]; then
        TEAM_PROMPTS+=("$3")
        shift 3
      else
        TEAM_PROMPTS+=("")
        shift 2
      fi
      ;;
    -dir)       DIR="${2:-}"; shift 2 ;;
    -session)   SESSION="${2:-}"; shift 2 ;;
    -no-attach) NO_ATTACH=1; shift ;;
    -h|--help)  usage; exit 0 ;;
    *)          echo "알 수 없는 옵션: $1" >&2; usage; exit 1 ;;
  esac
done

# ── -agent N 처리: 번호 기반 팀 자동 생성 ───────────────────
if [[ -n "$AGENT_SIZE" ]]; then
  if [[ ${#TEAM_NAMES[@]} -gt 0 ]]; then
    echo "Error: -agent 와 -team 은 동시에 사용 불가" >&2; exit 1
  fi
  if ! [[ "$AGENT_SIZE" =~ ^[0-9]+$ ]] || (( AGENT_SIZE < 2 )); then
    echo "Error: -agent 최소값은 2 (Team Leader + Agent 1)" >&2; exit 1
  fi
  if (( AGENT_SIZE > 11 )); then
    echo "Error: -agent 최대값은 11 (Team Leader + Agent 10)" >&2; exit 1
  fi
  for (( i=1; i<=AGENT_SIZE-1; i++ )); do
    TEAM_NAMES+=("agent-$i")
    TEAM_PROMPTS+=("")
  done
fi

# ── 유효성 검사 ──────────────────────────────────────────────
TEAM_COUNT=${#TEAM_NAMES[@]}

if (( TEAM_COUNT == 0 )); then
  echo "Error: -agent N 또는 -team NAME 을 지정해야 함" >&2; usage; exit 1
fi
if (( TEAM_COUNT > 10 )); then
  echo "Error: 최대 10팀 (Agent 10)" >&2; exit 1
fi

DIR="${DIR/#\~/$HOME}"
if [[ ! -d "$DIR" ]]; then
  echo "Error: 디렉토리 없음: $DIR" >&2; exit 1
fi
DIR=$(cd "$DIR" && pwd)

if [[ -z "$SESSION" ]]; then
  SLUG=$(basename "$DIR" | tr -c '[:alnum:]_-' '-' | sed 's/-\+/-/g; s/^-//; s/-$//')
  [[ -z "$SLUG" ]] && SLUG="root"
  SESSION="subagent-$SLUG"
fi

if ! command -v claude >/dev/null 2>&1; then
  echo "Warning: 'claude' 명령을 PATH에서 찾을 수 없음" >&2
fi

CLAUDE_CMD="claude --dangerously-skip-permissions"

# ── 팀 이름 중복 체크 ────────────────────────────────────────
declare -A _seen
for name in "${TEAM_NAMES[@]}"; do
  [[ -n "${_seen[$name]:-}" ]] && { echo "Error: 팀 이름 중복: $name" >&2; exit 1; }
  _seen["$name"]=1
done

# ── 헬퍼 생성 ────────────────────────────────────────────────
write_subagent_helper() {
  local helper_dir="$DIR/.claude-subagent"
  mkdir -p "$helper_dir"

  # 이름 → pane 인덱스 매핑 (1-based, Leader=0)
  local name_map_lines=""
  local list_lines=""
  for i in "${!TEAM_NAMES[@]}"; do
    local n=$(( i + 1 ))
    name_map_lines+="    [\"${TEAM_NAMES[$i]}\"]=$n"$'\n'
    list_lines+="  $n → Agent-$n  (${TEAM_NAMES[$i]})  $SESSION:0.$n"$'\n'
  done

  cat > "$helper_dir/team" <<TEAMEOF
#!/usr/bin/env bash
# Auto-generated by claude-subagent.sh
# Session: $SESSION  Teams: ${TEAM_NAMES[*]}
set -euo pipefail

SESSION="$SESSION"
AGENT_COUNT=$TEAM_COUNT

declare -A NAME_TO_IDX=(
$name_map_lines)

TEAM_NAMES=(${TEAM_NAMES[*]})

usage() {
  cat <<EOF2
Usage: \$(basename "\$0") <command> [args]

Commands:
  list                       팀 목록 (이름 + Agent 번호)
  send <NAME|N> <message>    팀에게 메시지 (이름 or 번호)
  broadcast <message>        모든 팀에게 메시지
  view <NAME|N> [lines]      팀 pane 출력 (기본 40줄)
  leader <message>           Team Leader pane에 메시지
  status                     각 pane 실행 상태 요약

Examples:
  ./.claude-subagent/team list
  ./.claude-subagent/team send interface "proto 작성해줘"
  ./.claude-subagent/team send 1 "proto 작성해줘"
  ./.claude-subagent/team broadcast "현재 상태 보고"
  ./.claude-subagent/team view interface 60
  ./.claude-subagent/team status
EOF2
}

check_session() {
  tmux has-session -t "\$SESSION" 2>/dev/null || {
    echo "Error: 세션 '\$SESSION' 없음" >&2; exit 1
  }
}

# 이름 또는 번호를 pane 인덱스로 변환
resolve() {
  local arg="\$1"
  # 숫자면 그대로
  if [[ "\$arg" =~ ^[0-9]+\$ ]]; then
    (( arg >= 1 && arg <= AGENT_COUNT )) || {
      echo "Error: 번호 범위 1..\$AGENT_COUNT" >&2; exit 1
    }
    echo "\$arg"; return
  fi
  # 이름 조회
  local idx="\${NAME_TO_IDX[\$arg]:-}"
  [[ -n "\$idx" ]] || {
    echo "Error: 팀 없음: '\$arg'  (사용 가능: \${!NAME_TO_IDX[*]})" >&2; exit 1
  }
  echo "\$idx"
}

send_to_pane() {
  tmux send-keys -t "\$1" -l "\$2"
  tmux send-keys -t "\$1" Enter
}

SUBCMD="\${1:-}"
shift || true

case "\$SUBCMD" in
  list)
    check_session
    echo "Session: \$SESSION"
    echo "  0 → Subagent / Team Leader  (\$SESSION:0.0)"
$list_lines
    ;;

  send)
    check_session
    TARGET="\${1:?'send <NAME|N> <message> 필요'}"
    shift
    MSG="\$*"
    [[ -n "\$MSG" ]] || { echo "Error: message 필요" >&2; exit 1; }
    IDX=\$(resolve "\$TARGET")
    send_to_pane "\$SESSION:0.\$IDX" "\$MSG"
    echo "→ [Agent-\$IDX / \${TEAM_NAMES[\$(( IDX - 1 ))]}]: \$MSG"
    ;;

  broadcast)
    check_session
    MSG="\$*"
    [[ -n "\$MSG" ]] || { echo "Error: message 필요" >&2; exit 1; }
    for (( i=1; i<=AGENT_COUNT; i++ )); do
      send_to_pane "\$SESSION:0.\$i" "\$MSG"
    done
    echo "→ 전체 \$AGENT_COUNT 팀: \$MSG"
    ;;

  view)
    check_session
    TARGET="\${1:?'view <NAME|N> 필요'}"
    LINES="\${2:-40}"
    IDX=\$(resolve "\$TARGET")
    LABEL="\${TEAM_NAMES[\$(( IDX - 1 ))]}"
    echo "── [Agent-\$IDX / \$LABEL] 최근 \$LINES 줄 ──────────────────"
    tmux capture-pane -pt "\$SESSION:0.\$IDX" -S "-\$LINES"
    ;;

  leader)
    check_session
    MSG="\$*"
    [[ -n "\$MSG" ]] || { echo "Error: message 필요" >&2; exit 1; }
    send_to_pane "\$SESSION:0.0" "\$MSG"
    echo "→ [Subagent / Team Leader]: \$MSG"
    ;;

  status)
    check_session
    printf "%-28s %-26s %s\n" "역할" "Pane" "실행 중"
    printf "%-28s %-26s %s\n" "────────────────────────────" "──────────────────────────" "────────"
    CMD=\$(tmux display-message -pt "\$SESSION:0.0" '#{pane_current_command}' 2>/dev/null || echo "?")
    printf "%-28s %-26s %s\n" "Subagent / Team Leader" "\$SESSION:0.0" "\$CMD"
    for (( i=1; i<=AGENT_COUNT; i++ )); do
      LABEL="\${TEAM_NAMES[\$(( i - 1 ))]}"
      CMD=\$(tmux display-message -pt "\$SESSION:0.\$i" '#{pane_current_command}' 2>/dev/null || echo "?")
      printf "%-28s %-26s %s\n" "Agent-\$i (\$LABEL)" "\$SESSION:0.\$i" "\$CMD"
    done
    ;;

  ""|-h|--help) usage ;;
  *) echo "Unknown: \$SUBCMD" >&2; usage; exit 1 ;;
esac
TEAMEOF
  chmod +x "$helper_dir/team"

  cat > "$helper_dir/README.md" <<READMEEOF
# Claude Sub-Agent Team

자동 생성됨 · 세션: \`$SESSION\`

| Agent | 팀 이름 | Pane |
|---|---|---|
| Team Leader | Subagent / Team Leader | \`$SESSION:0.0\` |
$(for i in "${!TEAM_NAMES[@]}"; do
  n=$(( i + 1 ))
  echo "| Agent-$n | ${TEAM_NAMES[$i]} | \`$SESSION:0.$n\` |"
done)

## 사용법

\`\`\`bash
./.claude-subagent/team list
./.claude-subagent/team send <이름|번호> "메시지"
./.claude-subagent/team broadcast "전체 공지"
./.claude-subagent/team view <이름|번호> [줄수]
./.claude-subagent/team status
\`\`\`
READMEEOF
}

# ── 현재 세션 보호 후 재생성 ─────────────────────────────────
if [[ -n "${TMUX:-}" ]]; then
  CURRENT_SESSION=$(tmux display-message -p '#{session_name}' 2>/dev/null || echo "")
  if [[ "$CURRENT_SESSION" == "$SESSION" ]]; then
    echo "Error: 현재 attach 중인 세션 '$SESSION' 재생성 불가. -session 으로 다른 이름 지정." >&2
    exit 1
  fi
fi
tmux kill-session -t "$SESSION" 2>/dev/null || true

tmux set-option -g history-limit 50000 >/dev/null
tmux new-session -d -s "$SESSION" -n main -c "$DIR" "$CLAUDE_CMD"

# ── 스타일링 (agentteams와 동일한 파란색) ────────────────────
tmux set-option -t "$SESSION" mouse on
tmux set-option -t "$SESSION" pane-border-status top
tmux set-option -t "$SESSION" pane-border-lines heavy
tmux set-option -t "$SESSION" pane-border-style "fg=colour39"
tmux set-option -t "$SESSION" pane-active-border-style "fg=colour39,bold"
tmux set-option -t "$SESSION" pane-border-format \
  '#{?pane_active,#[fg=colour15#,bg=colour27#,bold] ━━ #{@role} ━━ ,#[fg=colour39#,bg=default] #{@role} }'

tmux bind-key -T root WheelUpPane \
  if-shell -F -t = "#{pane_in_mode}" "send-keys -M" "copy-mode -eu"
tmux bind-key -T copy-mode    WheelUpPane   send-keys -X -N 5 scroll-up
tmux bind-key -T copy-mode    WheelDownPane send-keys -X -N 5 scroll-down
tmux bind-key -T copy-mode-vi WheelUpPane   send-keys -X -N 5 scroll-up
tmux bind-key -T copy-mode-vi WheelDownPane send-keys -X -N 5 scroll-down

# ── pane 구성 ────────────────────────────────────────────────
LEADER=$(tmux display-message -t "$SESSION:main" -p '#{pane_id}')
tmux set-option -pt "$LEADER" @role "Subagent / Team Leader"

PANE_IDS=()
PREV="$LEADER"

for i in "${!TEAM_NAMES[@]}"; do
  n=$(( i + 1 ))
  if (( i == 0 )); then
    PANE_ID=$(tmux split-window -h -t "$LEADER" -c "$DIR" -P -F '#{pane_id}' "$CLAUDE_CMD")
  else
    PANE_ID=$(tmux split-window -v -t "$PREV" -c "$DIR" -P -F '#{pane_id}' "$CLAUDE_CMD")
  fi
  tmux set-option -pt "$PANE_ID" @role "Agent-$n"
  PANE_IDS+=("$PANE_ID")
  PREV="$PANE_ID"
done

# 크기 조정
W_WIDTH=$(tmux display-message -t "$LEADER" -p '#{window_width}')
tmux resize-pane -t "$LEADER" -x $(( W_WIDTH / 2 ))

if (( TEAM_COUNT > 1 )); then
  W_HEIGHT=$(tmux display-message -t "$LEADER" -p '#{window_height}')
  EACH=$(( (W_HEIGHT - 1) / TEAM_COUNT ))
  (( EACH < 3 )) && EACH=3
  for pid in "${PANE_IDS[@]}"; do
    tmux resize-pane -t "$pid" -y "$EACH" 2>/dev/null || true
  done
fi

tmux select-pane -t "$LEADER"

# ── 헬퍼 생성 ────────────────────────────────────────────────
write_subagent_helper

# ── 초기 프롬프트 주입 ───────────────────────────────────────
INJECT_NEEDED=0
for prompt in "${TEAM_PROMPTS[@]}"; do
  [[ -n "$prompt" ]] && INJECT_NEEDED=1
done

if (( INJECT_NEEDED )); then
  (
    sleep 4
    for i in "${!TEAM_NAMES[@]}"; do
      prompt="${TEAM_PROMPTS[$i]}"
      [[ -z "$prompt" ]] && continue
      pane_id="${PANE_IDS[$i]}"
      if [[ -f "$prompt" ]]; then
        prompt_text="$(cat "$prompt")"
      else
        prompt_text="$prompt"
      fi
      tmux send-keys -t "$pane_id" -l "$prompt_text"
      tmux send-keys -t "$pane_id" Enter
    done
  ) &
fi

# ── 완료 안내 ────────────────────────────────────────────────
cat <<BANNER >&2

✓ Claude Sub-Agent Team 준비 완료
  세션:    $SESSION
  구성:    Subagent / Team Leader + Agent ${TEAM_COUNT}명
  팀 매핑:
$(for i in "${!TEAM_NAMES[@]}"; do
  n=$(( i + 1 ))
  echo "    Agent-$n → ${TEAM_NAMES[$i]}"
done)
  헬퍼:    ./.claude-subagent/team

  사용 예:
    ./.claude-subagent/team list
    ./.claude-subagent/team send interface "작업 지시"
    ./.claude-subagent/team send 1 "작업 지시"
    ./.claude-subagent/team broadcast "상태 보고"
    ./.claude-subagent/team status

BANNER

if (( INJECT_NEEDED )); then
  echo "  초기 프롬프트: 4초 후 각 Agent pane에 자동 주입" >&2
  echo "" >&2
fi

# ── attach / switch ──────────────────────────────────────────
if (( NO_ATTACH )) || [[ ! -t 1 ]]; then
  cat <<HINT >&2
✓ 세션 '$SESSION' 생성 완료 (attach 생략)
  tmux attach -t $SESSION
  tmux switch-client -t $SESSION
HINT
  exit 0
fi

if [[ -n "${TMUX:-}" ]]; then
  tmux switch-client -t "$SESSION"
else
  tmux attach-session -t "$SESSION"
fi
